# python-socketio 5.17.0의 예외(스텁). typings/socketio/__init__.pyi의 설명을 본다.
from typing import Any

class SocketIOError(Exception): ...
class ConnectionError(SocketIOError): ...

class ConnectionRefusedError(ConnectionError):
    error_args: dict[str, Any]
    def __init__(self, *args: Any) -> None: ...

class TimeoutError(SocketIOError): ...
