import { describe, expect, it } from "vitest";
import { checkHarness } from "./harness";

const base = {
  "AGENTS.md": "# 지침\n",
  "CLAUDE.md": "@AGENTS.md\n",
  ".env.example": "A=one\nB=two\n",
};
const inspect = (files: Record<string, string>) => checkHarness(files, ["A", "B"]);

it.each([3000, 3001])("앱 %s의 목 API·실시간 예시 포트를 검사한다", (dev) => {
  const mock = dev + 1010;
  const files = {
    ...base,
    "app.config.json": JSON.stringify({
      app: "example",
      ports: { dev, mock, e2e: dev + 100, e2eMock: mock + 100 },
    }),
    "package.json": JSON.stringify({ scripts: { start: `next start --port ${dev}` } }),
    ".env.example": `API_BASE_URL=http://localhost:${mock}/api/v1\nNEXT_PUBLIC_REALTIME_URL=http://localhost:${mock}\nAPP_URL=http://localhost:${dev}\n`,
  };
  const keys = ["API_BASE_URL", "NEXT_PUBLIC_REALTIME_URL", "APP_URL"];
  expect(checkHarness(files, keys)).toEqual([]);
  expect(
    checkHarness(
      { ...files, ".env.example": files[".env.example"].replaceAll(String(mock), "9999") },
      keys,
    ),
  ).toEqual([
    `.env.example:1 환경 — API_BASE_URL: app.config.json의 mock 포트로 고친다: http://localhost:${mock}/api/v1`,
    `.env.example:1 환경 — NEXT_PUBLIC_REALTIME_URL: app.config.json의 mock 포트로 고친다: http://localhost:${mock}`,
  ]);
});

it("동기화한 계약은 원본 배너를 보존한다", () => {
  expect(
    inspect({
      ...base,
      "contract/openapi.yaml": "openapi: 3.1.0\n",
      "contract/mock/src/generated/api.ts":
        "/**\n * This file was auto-generated by openapi-typescript.\n */\n",
    }),
  ).toEqual([]);
});

describe("하네스", () => {
  it("운영 start 포트가 앱 설정과 다르면 고칠 값을 알린다", () => {
    const files = {
      ...base,
      "app.config.json": JSON.stringify({
        app: "web",
        ports: { dev: 3000, mock: 4010, e2e: 3100, e2eMock: 4110 },
      }),
      "package.json": JSON.stringify({ scripts: { start: "next start --port 3001" } }),
    };
    expect(inspect(files)).toEqual([
      "package.json:1 start — app.config.json의 dev 포트로 고친다: next start --port 3000",
    ]);
    expect(
      inspect({
        ...files,
        "package.json": JSON.stringify({ scripts: { start: "next start --port 3000" } }),
      }),
    ).toEqual([]);
  });

  it(".env.example의 APP_URL이 앱 설정의 dev 포트와 다르면 고칠 값을 알린다", () => {
    const files = {
      ...base,
      "app.config.json": JSON.stringify({
        app: "web",
        ports: { dev: 3000, mock: 4010, e2e: 3100, e2eMock: 4110 },
      }),
      "package.json": JSON.stringify({ scripts: { start: "next start --port 3000" } }),
    };
    const withAppUrl = (url: string) =>
      checkHarness({ ...files, ".env.example": `A=one\nB=two\nAPP_URL=${url}\n` }, [
        "A",
        "B",
        "APP_URL",
      ]);
    expect(withAppUrl("http://localhost:3001")).toEqual([
      ".env.example:1 환경 — APP_URL을 app.config.json의 dev 포트로 고친다: http://localhost:3000",
    ]);
    expect(withAppUrl("http://localhost:3000")).toEqual([]);
    expect(withAppUrl("  http://localhost:3000/path?key=value  # 개발 주소")).toEqual([]);
    expect(withAppUrl("잘못된 URL")).toEqual([
      ".env.example:1 환경 — APP_URL을 app.config.json의 dev 포트로 고친다: http://localhost:3000",
    ]);
    expect(
      checkHarness(
        { ...files, ".env.example": "A=one\nB=two\nAPP_URL = http://localhost:3000\n" },
        ["A", "B", "APP_URL"],
      ),
    ).toEqual([]);
  });

  it("정상 파일을 통과시킨다", () => expect(inspect(base)).toEqual([]));
  it("양방향 지침 짝과 CLAUDE 내용을 검사한다", () => {
    expect(inspect({ ...base, "src/AGENTS.md": "규칙" }).join()).toMatch(/CLAUDE/);
    expect(inspect({ ...base, "src/CLAUDE.md": "@AGENTS.md" }).join()).toMatch(/AGENTS/);
    expect(inspect({ ...base, "CLAUDE.md": "다른 규칙" }).join()).toMatch(/@AGENTS.md/);
    const { "AGENTS.md": _agents, ...missing } = base;
    expect(inspect(missing).join()).toMatch(/AGENTS/);
  });
  it("루트 200줄, 소스 400줄, 테스트 600줄 한도를 지킨다", () => {
    expect(inspect({ ...base, "AGENTS.md": "x\n".repeat(201) }).join()).toMatch(/200/);
    expect(inspect({ ...base, "src/a.ts": "\n".repeat(401) }).join()).toMatch(/400/);
    expect(inspect({ ...base, "src/a.test.ts": "\n".repeat(601) }).join()).toMatch(/600/);
    expect(inspect({ ...base, "src/a.ts": "\n".repeat(400) })).toEqual([]);
    expect(inspect({ ...base, "src/a.test.ts": "\n".repeat(600) })).toEqual([]);
  });
  it.each([
    "// eslint-disable-next-line no-console",
    "// @ts-ignore",
    "// @ts-expect-error",
    "// @ts-nocheck",
    "let value: any;",
  ])("사유 없는 억제를 막는다: %s", (code) => {
    expect(inspect({ ...base, "src/a.ts": code }).join()).toMatch(/사유/);
    expect(inspect({ ...base, "src/a.ts": `${code} // 사유: 외부 경계 타입 확인\n` })).toEqual([]);
  });
  it("문자열 속 예시와 일반 주석의 any는 억제로 보지 않는다", () => {
    expect(
      inspect({
        ...base,
        "src/a.ts": 'const text = "any @ts-ignore eslint-disable";\n// any 값 설명\n',
      }),
    ).toEqual([]);
  });
  it.each([
    'let value: any = "reason: this is string content";',
    "let value: any = `x${1}// reason: this is string content`;",
    "let value: any = `x${1}/* reason: this is string content */`;",
    "let value: any = count-- + 12345;",
    '/* @ts-ignore */ const value = "reason: this is string content";',
    "/* @ts-nocheck */ // reason: unrelated comment",
  ])("문자열·연산자·다른 주석을 억제 사유로 인정하지 않는다: %s", (code) => {
    expect(inspect({ ...base, "src/a.ts": code }).join()).toMatch(/사유/);
  });
  it.each([
    "// @ts-nocheck -- 외부 라이브러리 경계",
    "/* @ts-ignore reason: external library boundary */",
    "let value: any; // reason: external library boundary",
    "let value: any = `x${1}// example`; // 사유: 외부 라이브러리 경계",
    "let value: any = `x${1 /* 사유: 외부 라이브러리 경계 */}`;",
  ])("같은 억제 주석과 any의 뒤따르는 주석에 적은 사유를 인정한다: %s", (code) => {
    expect(inspect({ ...base, "src/a.ts": code })).toEqual([]);
  });
  it("환경 예시의 빠진 키와 남는 키를 모두 검사한다", () => {
    const result = inspect({ ...base, ".env.example": "A=x\nC=y\n" }).join();
    expect(result).toMatch(/B/);
    expect(result).toMatch(/C/);
  });
  it("생성물의 첫 줄 헤더를 검사하고 크기와 억제는 제외한다", () => {
    expect(inspect({ ...base, "src/generated/a.ts": "export {};" }).join()).toMatch(
      /직접 수정 금지/,
    );
    expect(inspect({ ...base, "src/lib/api/schema.d.ts": "export {};" }).join()).toMatch(
      /직접 수정 금지/,
    );
    expect(
      inspect({
        ...base,
        "src/generated/a.ts": "// 직접 수정 금지\n" + "let x: any;\n".repeat(700),
      }),
    ).toEqual([]);
  });
});
